os: linux
language: php
dist: bionic
php:
  - 7.3
  - 7.4
install:
  - composer install
script:
  - vendor/bin/phpunit --coverage-clover coverage.xml
  - vendor/bin/phpcs --runtime-set ignore_warnings_on_exit -p --extensions=php src
  - vendor/bin/phpmd src ansi phpmd.xml
  - vendor/bin/phpstan analyse src --level=0
after_success:
  - bash <(curl -s https://codecov.io/bash)
