os: linux
language: php
dist: bionic
php:
  - 7.3
  - 7.4
install:
  - composer install
script:
  - vendor/bin/phpunit --coverage-clover coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
